@baseUrl = http://localhost:7000

#Health check
GET {{baseUrl}}/health/  


### Create order

### Create order through gateway
POST {{baseUrl}}/orders/
Content-Type: application/json
Accept: application/json

{
    "userId": "mishc",
    "email": "misha@example.com",
    "address": "Street 12",
    "city": "Bergen",
    "postalCode": "5000",
    "country": "Norway"
}
      