@baseUrl = http://localhost:5001

### Get all products
GET {{baseUrl}}/api/products
Accept: application/json

### Get product by id
GET {{baseUrl}}/api/products/1
Accept: application/json

### Create product
POST {{baseUrl}}/api/products
Content-Type: application/json
Accept: application/json

{   
    "id": 4,
    "name": "Example Product",
    "price": 9.99,
}