using CatalogService.Endpoints;
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddDbContext<CatalogDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddStackExchangeRedisCache(options =>
{
    options.Configuration = builder.Configuration.GetConnectionString("Redis");
    options.InstanceName = "catalog-service:";
});

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();

app.MapProductEndpoints();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<CatalogDbContext>();
    var environment = scope.ServiceProvider.GetRequiredService<IWebHostEnvironment>();

    var retries = 10;

    while (retries > 0)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS catalog (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" text NOT NULL,
                    "Price" numeric(18,2) NOT NULL
                );
                """);

            await CatalogSeeder.SeedAsync(db, environment);
            break;
        }
        catch
        {
            retries--;
            await Task.Delay(2000);
        }
    }
}

app.Run();
